-- AMOEBA Experiment: Subquery Approach (Inefficient)
-- Find customers whose total order value exceeds 100,000
SELECT C_CUSTKEY, C_NAME, C_ACCTBAL
FROM {CUSTOMER_TABLE}
WHERE C_CUSTKEY IN (
    SELECT O_CUSTKEY
    FROM {ORDERS_TABLE}
    WHERE O_CUSTKEY = C_CUSTKEY
    AND O_TOTALPRICE > 100000
)
ORDER BY C_ACCTBAL DESC;
