-- AMOEBA Experiment: JOIN Approach (Efficient)
-- Find customers whose total order value exceeds 100,000
SELECT DISTINCT C.C_CUSTKEY, C.C_NAME, C.C_ACCTBAL
FROM {CUSTOMER_TABLE} C
INNER JOIN {ORDERS_TABLE} O ON C.C_CUSTKEY = O.O_CUSTKEY
WHERE O.O_TOTALPRICE > 100000
ORDER BY C.C_ACCTBAL DESC;

