/* Selecting customers total spent

Query 3B JOIN with GROUP BY
*/
SELECT C.C_CUSTKEY, C.C_NAME, SUM(O.O_TOTALPRICE) AS TOTAL_SPENT
FROM CUSTOMER C
LEFT JOIN ORDERS O ON C.C_CUSTKEY = O.O_CUSTKEY
GROUP BY C.C_CUSTKEY, C.C_NAME;

